// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDnAZDOqCTozQab2Oa4jVrlCcZXEoNL5jk",
      authDomain: "app-avicola.firebaseapp.com",
      projectId: "app-avicola",
      storageBucket: "app-avicola.appspot.com",
      messagingSenderId: "1071513662784",
      appId: "1:1071513662784:web:8859a4742db86949c9f6a5",
      measurementId: "G-GCX28ZJ54K"
  );


  static const FirebaseOptions android = FirebaseOptions(
     apiKey: "AIzaSyDnAZDOqCTozQab2Oa4jVrlCcZXEoNL5jk",
      projectId: "app-avicola",
      storageBucket: "app-avicola.appspot.com",
      messagingSenderId: "1071513662784",
      appId: "1:1071513662784:web:8859a4742db86949c9f6a5",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsBUIf4DUXpLmrDpJLQZ-h5WOSEep3gtk',
    appId: '1:354908197294:ios:583b2d498b27e9713b783f',
    messagingSenderId: '354908197294',
    projectId: 'progmovil-nggv',
    storageBucket: 'progmovil-nggv.appspot.com',
    iosClientId: '354908197294-9ct5fpjjb49o5e7f6as4h4v5kk0jf38u.apps.googleusercontent.com',
    iosBundleId: 'com.example.delivery',
  );
}
